# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: User

# Model Form Field configuration
form: $/jlab/users/models/user/fields.yaml

# Model Class name
modelClass: \Backend\Models\User

# Default redirect location
defaultRedirect: jlab/users/users

# Create page
create:
    title: Create User
    redirect: jlab/users/users/update/:id
    redirectClose: jlab/users/users

# Update page
update:
    title: Edit User
    redirect: jlab/users/users
    redirectClose: jlab/users/users

# Preview page
preview:
    title: Preview User
