# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: User

# Model Form Field configuration
form: $/bookrr/users/models/user/fields.yaml

# Model Class name
modelClass: \Backend\Models\User

# Default redirect location
defaultRedirect: bookrr/users/users

# Create page
create:
    title: Create User
    redirect: bookrr/users/users/update/:id
    redirectClose: bookrr/users/users

# Update page
update:
    title: Edit User
    redirect: bookrr/users/users
    redirectClose: bookrr/users/users

# Preview page
preview:
    title: Preview User
