# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Auth

# Model Form Field configuration
form: $/ocs/users/models/auth/fields.yaml

# Model Class name
modelClass: Ocs\Users\Models\Auth

# Default redirect location
defaultRedirect: ocs/users/auth

# Create page
create:
    title: Create Auth
    redirect: ocs/users/auth/update/:id
    redirectClose: ocs/users/auth

# Update page
update:
    title: Edit Auth
    redirect: ocs/users/auth
    redirectClose: ocs/users/auth

# Preview page
preview:
    title: Preview Auth
