# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Role

# Model Form Field configuration
form: $/bookrr/users/models/role/fields.yaml

# Model Class name
modelClass: Bookrr\Users\Models\Role

# Default redirect location
defaultRedirect: bookrr/users/role

# Create page
create:
    title: Create Role
    redirect: bookrr/users/role/update/:id
    redirectClose: bookrr/users/role

# Update page
update:
    title: Edit Role
    redirect: bookrr/users/role
    redirectClose: bookrr/users/role

# Preview page
preview:
    title: Preview Role
